# Generated by Django 3.0.8 on 2020-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='light', max_length=5),
        ),
    ]